--HOMEWORK AVIANCA
--JULIAN DAVID V�SQUEZ P�REZ
--RONALD RENDON ATEHORTUA

--USEFUL QUERIES
SELECT * FROM DBA_USERS;
SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME FROM DBA_TABLES WHERE TABLESPACE_NAME = 'AVIANCA';
SELECT * FROM DBA_PROFILES;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
GRANT CREATE SESSION TO DBA_AVIANCA WITH ADMIN OPTION

CREATE TABLESPACE AVIANCA
DATAFILE 'C:\AviancaDataFile\AVIANCADATAFILE.dat' SIZE 2G
ONLINE;

CREATE UNDO TABLESPACE UNDOAVIANCA
DATAFILE 'C:\AviancaDataFile\AVIANCAUNDODATAFILE.dat' SIZE 25M 
AUTOEXTEND ON;

--DBAAVIANCA IS THE DBA SYSTEM AVIANCA
CREATE USER DBA_AVIANCA 
    IDENTIFIED BY DBA_AVIANCA 
    DEFAULT TABLESPACE AVIANCA 
    QUOTA UNLIMITED ON AVIANCA;

CREATE PROFILE CLERK LIMIT
    PASSWORD_LIFE_TIME 40
    SESSIONS_PER_USER 1
    IDLE_TIME 10
    FAILED_LOGIN_ATTEMPTS 4;

CREATE PROFILE DEVELOPMENT LIMIT
    PASSWORD_LIFE_TIME 100
    SESSIONS_PER_USER 2
    IDLE_TIME 30
    FAILED_LOGIN_ATTEMPTS UNLIMITED;

--CREATION OF TABLES
CREATE TABLE ESTADOS(
    ID_ESTADO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255)
)
TABLESPACE AVIANCA;

CREATE TABLE TIPOS_EMPLEADOS(
    ID_TIPO_EMPLEADO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255)
)
TABLESPACE AVIANCA;

CREATE TABLE NIVELES_INGLES(
    ID_NIVEL_INGLES NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255)
)
TABLESPACE AVIANCA;

CREATE TABLE TIPOS_LICENCIAS(
    ID_TIPO_LICENCIA NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255)
)
TABLESPACE AVIANCA;

CREATE TABLE CARGOS_PILOTO(
    ID_CARGO_PILOTO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255)
)
TABLESPACE AVIANCA;

CREATE TABLE EMPLEADOS(
    ID_EMPLEADO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    GENERO CHAR(1),
    FECHA_NACIMIENTO DATE NOT NULL,
    ANTIGUEDAD NUMERIC,
    FECHA_ENTRENAMIENTO DATE,
    DIRECCION VARCHAR(255),
    EMAIL VARCHAR(255),
    NUMERO_CELULAR VARCHAR(30),
    HORAS_DESCANSO NUMERIC,
    HORAS_VUELO NUMERIC,
    ID_ESTADO NUMERIC,
    ID_NIVEL_INGLES NUMERIC,
    ID_TIPO_EMPLEADO NUMERIC,
    ID_TIPO_LICENCIA NUMERIC,
    ID_CARGO_PILOTO NUMERIC,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO),
    FOREIGN KEY (ID_NIVEL_INGLES) REFERENCES NIVELES_INGLES(ID_NIVEL_INGLES),
    FOREIGN KEY (ID_TIPO_EMPLEADO) REFERENCES TIPOS_EMPLEADOS(ID_TIPO_EMPLEADO),
    FOREIGN KEY (ID_TIPO_LICENCIA) REFERENCES TIPOS_LICENCIAS(ID_TIPO_LICENCIA),
    FOREIGN KEY (ID_CARGO_PILOTO) REFERENCES CARGOS_PILOTO(ID_CARGO_PILOTO)
)
TABLESPACE AVIANCA;

CREATE TABLE TIPOS_AVIONES(
    ID_TIPO_AVION NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    TIPO VARCHAR(255),
    ASIENTOS_EJECUTIVOS NUMERIC,
    ASIENTOS_ECONOMICOS NUMERIC
)
TABLESPACE AVIANCA;

CREATE TABLE AVIONES(
    ID_AVION NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    MATRICULA VARCHAR(255) NOT NULL,
    SERIAL VARCHAR(255),
    EDAD NUMERIC NULL,
    ID_TIPO_AVION NUMERIC,
    FOREIGN KEY (ID_TIPO_AVION) REFERENCES TIPOS_AVIONES(ID_TIPO_AVION)
)
TABLESPACE AVIANCA;

CREATE TABLE PAISES(
    ID_PAIS NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255)
)
TABLESPACE AVIANCA;

CREATE TABLE CIUDADES(
    ID_CIUDAD NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255),
    ID_PAIS NUMERIC,
    FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID_PAIS)
)
TABLESPACE AVIANCA;

CREATE TABLE AEROPUERTOS(
    ID_AEROPUERTO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    ABREVIATURA VARCHAR(255) NOT NULL,
    NOMBRE_AEROPUERTO VARCHAR(255) NOT NULL,
    LATITUD VARCHAR(255),
    LONGITUD VARCHAR(255),
    ID_CIUDAD NUMERIC,
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD)
)
TABLESPACE AVIANCA;

CREATE TABLE RUTAS(
    ID_RUTA NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DISTANCIA NUMERIC NOT NULL,
    ID_AEROPUERTO_ORIGEN NUMERIC,
    ID_AEROPUERTO_DESTINO NUMERIC,
    FOREIGN KEY (ID_AEROPUERTO_ORIGEN) REFERENCES AEROPUERTOS(ID_AEROPUERTO),
    FOREIGN KEY (ID_AEROPUERTO_DESTINO) REFERENCES AEROPUERTOS(ID_AEROPUERTO)
)
TABLESPACE AVIANCA;

CREATE TABLE RUTAS_TIPOS_AVIONES(
    ID_RUTAS_TIPOS_AVIONES NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    ID_RUTA NUMERIC,
    ID_TIPO_AVION NUMERIC,
    FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA),
    FOREIGN KEY (ID_TIPO_AVION) REFERENCES TIPOS_AVIONES(ID_TIPO_AVION)
)
TABLESPACE AVIANCA;

CREATE TABLE TIPOS_DOCUMENTOS(
    ID_TIPO_DOCUMENTO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255)
)
TABLESPACE AVIANCA;

CREATE TABLE PASAJEROS(
    ID_PASAJERO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    NUMERO_DNI VARCHAR(255),
    ID_TIPO_DOCUMENTO NUMERIC,
    ID_PAIS NUMERIC,
    FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOCUMENTO),
    FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID_PAIS)
)
TABLESPACE AVIANCA;

CREATE TABLE ITINERARIOS(
    ID_ITINERARIO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NUMERO_VUELO VARCHAR(25) NOT NULL,
    PROMEDIO_HORAS NUMERIC,
    FECHA_VUELO DATE,
    DIA VARCHAR(25),
    HORA VARCHAR(35),
    FRECUENCIA_SEMANAL NUMERIC,
    ID_RUTA NUMERIC,
    ID_AVION NUMERIC,
    FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA),
    FOREIGN KEY (ID_AVION) REFERENCES AVIONES(ID_AVION)
)
TABLESPACE AVIANCA;

CREATE TABLE VUELOS_CONFIRMADOS(
    ID_VUELO_CONFIRMADO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    HORA_ESTIMADA_SALIDA VARCHAR(35),
    HORA_ESTIMADA_LLEGADA VARCHAR(35),
    HORA_REAL_SALIDA VARCHAR(35),
    HORA_REAL_LLEGADA VARCHAR(35),
    DURACION_REAL NUMERIC,
    CANTIDAD_PASAJEROS NUMERIC,
    CANTIDAD_TCP NUMERIC,
    ID_ITINERARIO NUMERIC,
    ID_EMPLEADO_PILOTO NUMERIC,
    ID_EMPLEADO_COPILOTO NUMERIC,
    FOREIGN KEY (ID_ITINERARIO) REFERENCES ITINERARIOS(ID_ITINERARIO),
    FOREIGN KEY (ID_EMPLEADO_PILOTO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY (ID_EMPLEADO_COPILOTO) REFERENCES EMPLEADOS(ID_EMPLEADO)
)
TABLESPACE AVIANCA;

CREATE TABLE AUXILIARES_VUELO_CONFIRMADO(
    ID_AUXILIARES_VUELO_CONFIRMADO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    ID_VUELO_CONFIRMADO NUMERIC,
    ID_EMPLEADO_AUXILIAR NUMERIC,
    FOREIGN KEY (ID_VUELO_CONFIRMADO) REFERENCES VUELOS_CONFIRMADOS(ID_VUELO_CONFIRMADO),
    FOREIGN KEY (ID_EMPLEADO_AUXILIAR) REFERENCES EMPLEADOS(ID_EMPLEADO)
)
TABLESPACE AVIANCA;

CREATE TABLE CHECK_IN(
    ID_CHECK_IN NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    CONTACTO_EMERGENCIA VARCHAR(255) NOT NULL,
    CORREO_CONTACTO VARCHAR(255),
    NUMERO_CELULAR VARCHAR(30),
    ID_CIUDAD NUMERIC,
    ID_PASAJERO NUMERIC,
    ID_VUELO_CONFIRMADO NUMERIC,
    FOREIGN KEY (ID_VUELO_CONFIRMADO) REFERENCES VUELOS_CONFIRMADOS(ID_VUELO_CONFIRMADO),
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD),
    FOREIGN KEY (ID_PASAJERO) REFERENCES PASAJEROS(ID_PASAJERO)
)
TABLESPACE AVIANCA;



CREATE USER DEV_RONALD
    IDENTIFIED BY DEV_RONALD
    DEFAULT TABLESPACE AVIANCA 
    QUOTA UNLIMITED ON AVIANCA
    PROFILE DEVELOPMENT;
    
  CREATE USER DEV_JULIAN
    IDENTIFIED BY DEV_JULIAN
    DEFAULT TABLESPACE AVIANCA 
    QUOTA UNLIMITED ON AVIANCA
    PROFILE DEVELOPMENT;
    
CREATE USER CK_ESPERANZA
    IDENTIFIED BY CK_ESPERANZA
    DEFAULT TABLESPACE AVIANCA 
    QUOTA UNLIMITED ON AVIANCA
    PROFILE CLERK;    
    
CREATE USER CK_MIA
    IDENTIFIED BY CK_MIA
    DEFAULT TABLESPACE AVIANCA 
    QUOTA UNLIMITED ON AVIANCA
    PROFILE CLERK;

ALTER USER DEV_JULIAN ACCOUNT UNLOCK;
ALTER USER CK_MIA ACCOUNT LOCK;
