--HOMEWORK AVIANCA
--JULIAN DAVID V�SQUEZ P�REZ

--USEFUL QUERIES
SELECT * FROM DBA_USERS;
SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;
SELECT * FROM DBA_PROFILES;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE TABLESPACE AVIANCA
DATAFILE 'C:\AviancaDataFile\AVIANCADATAFILE.dat' SIZE 2G
ONLINE;

CREATE UNDO TABLESPACE UNDOAVIANCA
DATAFILE 'C:\AviancaDataFile\AVIANCAUNDODATAFILE.dat' SIZE 25M 
AUTOEXTEND ON;

--DBAAVIANCA IS THE DBA SYSTEM AVIANCA
CREATE USER DBAAVIANCA 
    IDENTIFIED BY DBAAVIANCA 
    DEFAULT TABLESPACE AVIANCA 
    QUOTA UNLIMITED ON AVIANCA;

CREATE PROFILE CLERK LIMIT
    PASSWORD_LIFE_TIME 40
    SESSIONS_PER_USER 1
    IDLE_TIME 10
    FAILED_LOGIN_ATTEMPTS 4;

CREATE PROFILE DEVELOPMENT LIMIT
    PASSWORD_LIFE_TIME 100
    SESSIONS_PER_USER 2
    IDLE_TIME 30
    FAILED_LOGIN_ATTEMPTS UNLIMITED;

    -- Comentarios--

