ALTER TABLE CIUDADES
DROP CONSTRAINT FK_ID_PAIS;

ALTER TABLE CHECK_IN
DROP CONSTRAINT SYS_C0010286;

ALTER TABLE AEROPUERTOS
DROP CONSTRAINT SYS_C0010250;

ALTER TABLE CIUDADES
ADD ID_PAIS NUMERIC;

ALTER TABLE CIUDADES
ADD CONSTRAINT FK_ID_PAIS
FOREIGN KEY (ID_PAIS) REFERENCES CIUDADES(ID_CIUDAD);

SELECT * FROM CIUDADES;
TRUNCATE TABLE CIUDADES;

DROP TABLE CIUDADES;

INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('COLOMBIA', NULL);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('ARGENTINA', NULL);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('PERU', NULL);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('ESDOS UNIDOS', NULL);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('MEDELLIN', 1);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('BOGOTA', 1);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('BUENOS AIRES', 2);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('LIMA', 3);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('CUSCO', 3);
INSERT INTO CIUDADES (DESCRIPCION, ID_PAIS) VALUES ('MIAMI', 4);

ALTER TABLE EMPLEADOS
DROP CONSTRAINT SYS_C0010231;

ALTER TABLE EMPLEADOS
DROP CONSTRAINT SYS_C0010232;

ALTER TABLE EMPLEADOS
DROP CONSTRAINT SYS_C0010233;

ALTER TABLE ITINERARIOS 
DROP COLUMN PROMEDIO_HORAS;

ALTER TABLE EMPLEADOS 
DROP COLUMN ID_TIPO_EMPLEADO;

ALTER TABLE EMPLEADOS 
DROP COLUMN ID_TIPO_LICENCIA;

ALTER TABLE EMPLEADOS
ADD (NIVEL_INGLES VARCHAR(255), TIPO_EMPLEADO VARCHAR(255), TIPO_LICENCIA VARCHAR(255));

ALTER TABLE RUTAS
ADD PROMEDIO_HORAS NUMBER;

ALTER TABLE ITINERARIOS
DROP CONSTRAINT SYS_C0010272;
ALTER TABLE ITINERARIOS 
DROP COLUMN ID_AVION;

ALTER TABLE VUELOS_CONFIRMADOS
ADD ID_AVION NUMBER;

ALTER TABLE VUELOS_CONFIRMADOS
ADD CONSTRAINT FK_ID_AVION
FOREIGN KEY (ID_AVION) REFERENCES AVIONES(ID_AVION);

ALTER TABLE CHECK_IN 
DROP COLUMN ID_CIUDAD;
SELECT * FROM CHECK_IN;
ALTER TABLE CHECK_IN
ADD ID_CIUDAD_CONTACTO_EMERGENCIA NUMERIC;

ALTER TABLE CHECK_IN
ADD CONSTRAINT FK_ID_CIUDAD_CONTACTO_EMER
FOREIGN KEY (ID_CIUDAD_CONTACTO_EMERGENCIA) REFERENCES CIUDADES(ID_CIUDAD);

ALTER TABLE AEROPUERTOS
ADD CONSTRAINT FK_ID_CIUDAD
FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD);

ALTER TABLE LOG_VUELOS
ADD ID_VUELO_CONFIRMADO NUMERIC;

ALTER TABLE LOG_VUELOS
ADD CONSTRAINT FK_ID_VUELOS
FOREIGN KEY (ID_VUELO_CONFIRMADO) REFERENCES VUELOS_CONFIRMADOS(ID_VUELO_CONFIRMADO);

DROP TABLE NIVELES_INGLES;
DROP TABLE TIPOS_EMPLEADOS;
DROP TABLE TIPOS_LICENCIAS;

ALTER TABLE AVIONES
ADD ESTADO VARCHAR(255);

ALTER TABLE VUELOS_CONFIRMADOS
ADD ESTADO VARCHAR(255);